# Generated by Django 4.1.3 on 2022-11-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="total_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
