# Generated by Django 4.1.3 on 2022-11-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_articlepost_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="article/%Y%m%d/"),
        ),
    ]
