# Generated by Django 4.1.3 on 2022-11-08 09:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="body", field=ckeditor.fields.RichTextField(),
        ),
    ]
